sudo: false
language: node_js
node_js:
  - 7
  - 8
script:
  - npm run lint
  - npm test
notifications:
  email:
    on_failure: change
cache:
  yarn: true
  bundler: true
  directories:
    - node_modules
before_script:
  - npm install styled-components react@15
